package importer

var synonims = map[string]string{
	"LiveBar":       "Лайвбар",
	"Lounge":        "Лаундж",
	"Hyatt":         "Хаят",
	"Issyk":         "Ыссык",
	"Kul":           "Куль",
	"Coffee":        "Кофе",
	"Alexsandra":    "Александра",
	"Beeline":       "Билайн",
	"Mega-Line":     "Мега-Лайн",
	"Center":        "Центр",
	"Mary":          "Мери",
	"Pizza":         "Пицца",
	"Park":          "Парк",
	"House":         "Хаус",
	"Trade":         "Трейд",
	"Bishkek":       "Бишкек",
	"Logic":         "Лоджик",
	"Rich":          "Рич",
	"School":        "Скул",
	"The":           "Зе",
	"Oriflame":      "Орифлейм",
	"Arzu":          "Арзу",
	"GrandStone":    "Грандстоун",
	"The Olive":     "Олив",
	"Trade college": "Трейд колледж",
	"Manchester":    "Манчестер",
	"Pertroleum":    "Петролеум",
	"Green City":    "Грин Сити",
	"My house":      "Май Хаус",
	"Way":           "Вей",
	"Boutique":      "Бутик",
	"Johnny":        "Джонни",
	"Green":         "Грин",
	"New":           "Нью",
	"Litech":        "Литек",
	"Burger":        "Бургер",
	"Brand":         "Бренд",
	"Movie":         "Муви",
	"Rose":          "Роуз",
	"Chicago":       "Чикаго",
	"Khalyk":        "Халык",
	"cup":           "Кап",
	"cake":          "Кейк",
	"EcoHouse":      "Эко хаус",
	"Club":          "Клаб",
	"Pub":           "Паб",
	"LLumarc":       "Люмарк",
	"Havai":         "Гаваи",
	"Lady's":        "Леди",
	"Mexx":          "Мехх",
	"Cinema":        "Синема",
	"CityNet":       "Ситинет",
	"The Host":      "Зе Хост",
	"Tunnel":        "Туннель",
	"München":       "Мюнхен",
	"Light":         "Лайт",
	"Style":         "Стайл",
	"Apple":         "Эпл",
	"Hotel":         "Отель",
	"LoveTime":      "ЛавТайм",
	"shop":          "шоп",
	"office":        "офис",
	"Interhouse":    "Интерхаус",
	"Dostuck":       "Достук",
	"Advantour":     "Адвантур",
	"Orthodox":      "Ортодокс",
	"Church":        "Церковь",
	"Store":         "Стор",
	"Showroom":      "Шоурум",
}
